[supervisord]
nodaemon=true

[program:nr-softmodem]
command=/opt/oai-gnb/bin/nr-softmodem
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
autorestart=true

[program:metrics-exporter]
command=python3 /opt/oai-gnb/gnb_metrics_exporter.py
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
autorestart=true