[supervisord]
nodaemon=true

[program:metrics-exporter]
command=python3 /opt/oai-gnb/gnb_metrics_exporter.py
autorestart=true

[program:nr-softmodem]
command=/opt/oai-gnb/bin/nr-softmodem
autorestart=true